CompanyEmployees.MVC/Controllers/CompanyManagerController.cs
using Contracts;
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompanyEmployees.MVC.Controllers
{
    [Authorize(Roles="Visitor,Manager")]
    public class CompanyManagerController : Controller
    {
        
        private IRepositoryManager _repositoryManager;

        public CompanyManagerController(IRepositoryManager repositoryManager)
        {
            _repositoryManager = repositoryManager;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            var companies = _repositoryManager.Company.GetAllCompanies(false);
            return View(companies);
        }
        [AllowAnonymous]
        public IActionResult Details(Guid id)
        {
            var company = _repositoryManager.Company.GetCompany(id, false);
            return View(company);
        }
        public IActionResult Insert()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Company model)
        {
            if (ModelState.IsValid)
            {
                _repositoryManager.Company.CreateCompany(model);
                _repositoryManager.Save();
                ViewBag.Message = "Bedrijf toegevoegd";
            }
            return View(model);
        }
        public IActionResult Update(Guid id)
        {

            Company model = _repositoryManager.Company.GetCompany(id, false);

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Company model)
        {
            //var form = HttpContext.Request.Form["Name"];
            if (ModelState.IsValid)
            {
                Company companyToUpdate = _repositoryManager.Company.GetCompany(model.Id, true);
                companyToUpdate.Name = model.Name;
                companyToUpdate.Address = model.Address;
                companyToUpdate.Country = model.Country;
                companyToUpdate.LaunchDate = model.LaunchDate;
                companyToUpdate.Description = model.Description;
                companyToUpdate.Size = model.Size;
                _repositoryManager.Save();
                ViewBag.Message = "Bedrijf is aangepast";
            }
            return View(model);
        }
        private void FillEmployeesForCompany(Guid companyId)
        {
            List<SelectListItem> employees = (from c in _repositoryManager.Employee.GetAllEmployees(false)
                                              where c.CompanyId == companyId
                                              orderby c.Name
                                              select new SelectListItem() { Text = c.Name, Value = c.Id.ToString() }).ToList();
            ViewBag.Employees = employees;
        }

        [ActionName("Delete")]
        public IActionResult ConfirmDelete(Guid id)
        {
            //int aantalEmployees = _repositoryManager.Employee.GetAllEmployees(false).Where(e => e.CompanyId == id).Count();
            //if (aantalEmployees > 0)
            //{
            //    ViewBag.Message = "Cannot remove Company, " + aantalEmployees + " employee(s) work here";
            //    return View(new Company());
            //}
            //else {
                ViewBag.Message = "Waarschuwing : U gaat dit bedrijf verwijderen!";
                Company company = _repositoryManager.Company.GetCompany(id, false);
                FillEmployeesForCompany(id);
                return View(company);
           // }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Guid id)
        {
            //int aantalEmployees = _repositoryManager.Employee.GetAllEmployees(false).Where(e => e.CompanyId == id).Count();
            //if (aantalEmployees > 0)
            //{
            //    ViewBag.Message = "Cannot remove Company, " + aantalEmployees + " employee(s) work here";
            //    return View(new Company());
            //}
            //else
            //{
                Company companyToDelete = _repositoryManager.Company.GetCompany(id, false);
                _repositoryManager.Company.DeleteCompany(companyToDelete);
                _repositoryManager.Save();

                TempData["Message"] = "Bedrijf verwijderd";
                return RedirectToAction(nameof(Index));
            //}
        }
    }
}

CompanyEmployees.MVC/Controllers/EmployeeManagerController.cs
using Contracts;
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompanyEmployees.MVC.Controllers
{
    [Authorize(Roles="Manager")]
    public class EmployeeManagerController : Controller
    {
        private IRepositoryManager _repositoryManager;

        public EmployeeManagerController(IRepositoryManager repositoryManager)
        {
            _repositoryManager = repositoryManager;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            var employees = _repositoryManager.Employee.GetAllEmployees(false);
            return View(employees);
        }
        [AllowAnonymous]
        public IActionResult Details(Guid id)
        {
            var employee = _repositoryManager.Employee.GetEmployee(id,false);
            return View(employee);
        }
        private void FillCompanies()
        {
            List<SelectListItem> companies = (from c in _repositoryManager.Company.GetAllCompanies(false)
                                              orderby c.Name
                                              select new SelectListItem() { Text = c.Name, Value = c.Id.ToString() }).ToList();
            ViewBag.Companies = companies;
        }
        public IActionResult Insert()
        {
            FillCompanies();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Employee model)
        {
            if (ModelState.IsValid)
            {
                _repositoryManager.Employee.CreateEmployeeForCompany(model.CompanyId, model);
                _repositoryManager.Save();
                ViewBag.Message = "Werknemer toegevoegd";
            }
            FillCompanies();
            return View(model);
        }

        public IActionResult Update(Guid id)
        {
            FillCompanies();

            Employee model = _repositoryManager.Employee.GetEmployee(id, false);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Employee model)
        {
            FillCompanies();

            if (ModelState.IsValid)
            {
                Employee employeeToUpdate = _repositoryManager.Employee.GetEmployee(model.Id, true);
                employeeToUpdate.Name = model.Name;
                employeeToUpdate.Position = model.Position;
                employeeToUpdate.Age = model.Age;
                employeeToUpdate.CompanyId = model.CompanyId;
                employeeToUpdate.Description = model.Description;
                employeeToUpdate.Gender = model.Gender;
                _repositoryManager.Save();
                ViewBag.Message = "Gegevens werknemer aangepast";
            }
            return View(model);
        }

        [ActionName("Delete")]
        public IActionResult ConfirmDelete(Guid id)
        {
            ViewBag.Message = "Opgelet: U gaat deze werknemer verwijderen!";
            Employee model = _repositoryManager.Employee.GetEmployee(id, false);
            Company company = _repositoryManager.Company.GetCompany(model.CompanyId, false);
            ViewBag.Company = company;
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Guid id)
        {
            Employee employeeToDelete = _repositoryManager.Employee.GetEmployee(id, false);
            _repositoryManager.Employee.DeleteEmployee(employeeToDelete);
            _repositoryManager.Save();
            TempData["Message"] = "Werknemer verwijderd";
            return RedirectToAction("Index");//nameof(Index) = "Index"
        }

    }
}

CompanyEmployees.MVC/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Insert" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp;  Nieuw </a>
</p>

CompanyEmployees.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompanyEmployees.MVC</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- <link rel="stylesheet" href="~/css/TableStyles.css" />-->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bedrijf en werknemers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse justify-content-between">
                    <ul class="navbar-nav align-content-end">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Security" asp-action="Register">Registreer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Security" asp-action="SignIn">Log in</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="EmployeeManager" asp-action="Index">Werknemers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="CompanyManager" asp-action="Index">Bedrijven</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br />
    <hr />

    @if (User.Identity.IsAuthenticated)
    {
        <h2>You are signed in as @User.Identity.Name</h2>
        <form asp-controller="Security" asp-action="SignOut" method="post">
            <button type="submit">Sign Out</button>
        </form>
    }

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-white">
            &copy; 2021 - Werknemers en bedrijven - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CompanyEmployees.MVC/Views/Shared/_TableButtonPartial.cshtml
@model Guid

<td >
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Update" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>

        <a class="btn btn-success text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>